; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Wed Apr 14 2021 01:55:04 GMT-0500 (Central Daylight Time)

M98 P"Commands/Probe/Deploy.g"