; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Wed Apr 14 2021 01:55:04 GMT-0500 (Central Daylight Time)

M98 P"Commands/Probe/Retract.g"

;;;var probeValue = sensors.probes[0].value[0]
;;;var probeThreshold = sensors.probes[0].threshold

; To avoid errors
;;;if var.probeValue >= var.probeThreshold
;;;    G4 P200
;;;    M280 P0 S160
