; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Wed Apr 14 2021 01:55:04 GMT-0500 (Central Daylight Time)
; Wait for set temperatures to be reached
M116 P0

